import { Topic, Problem } from "./types";

// ═══════════════════════════════════════════════════════════════
// ROADMAP COMPLETO: De CERO ABSOLUTO a EXPERTO en Matemáticas
// 10 Niveles · 60+ Subtemas · 150+ Problemas con hints y soluciones
// ═══════════════════════════════════════════════════════════════

export const seedTopics: Topic[] = [
  // ═══ NIVEL 0: Pre-Aritmética y Aritmética Fundamental ═══
  {
    id: "t-0",
    level: 0,
    title: "Aritmética Fundamental",
    description: "Los cimientos absolutos: operaciones básicas, fracciones, decimales, porcentajes y el orden de operaciones.",
    parent_topic_id: null,
    is_locked_by_default: false,
  },
  {
    id: "t-0-1",
    level: 0,
    title: "Operaciones Básicas",
    description: "Suma, resta, multiplicación y división de enteros. Propiedades conmutativa, asociativa y distributiva.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },
  {
    id: "t-0-2",
    level: 0,
    title: "Fracciones",
    description: "Suma, resta, multiplicación, división y simplificación de fracciones. Fracciones mixtas e impropias.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },
  {
    id: "t-0-3",
    level: 0,
    title: "Decimales y Redondeo",
    description: "Operaciones con decimales, conversión fracción-decimal, redondeo y notación científica.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },
  {
    id: "t-0-4",
    level: 0,
    title: "Porcentajes",
    description: "Cálculo de porcentajes, descuentos, aumentos, conversiones fracción-decimal-porcentaje.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },
  {
    id: "t-0-5",
    level: 0,
    title: "Orden de Operaciones (PEMDAS)",
    description: "Jerarquía de operaciones, uso de paréntesis, evaluación de expresiones numéricas complejas.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },
  {
    id: "t-0-6",
    level: 0,
    title: "Razones y Proporciones",
    description: "Razones, proporciones directas e inversas, regla de tres simple y compuesta.",
    parent_topic_id: "t-0",
    is_locked_by_default: false,
  },

  // ═══ NIVEL 1: Pre-Álgebra ═══
  {
    id: "t-1",
    level: 1,
    title: "Pre-Álgebra",
    description: "El puente entre aritmética y álgebra: números negativos, potencias, raíces y expresiones básicas.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-1-1",
    level: 1,
    title: "Números Enteros y Valor Absoluto",
    description: "Recta numérica, operaciones con negativos, valor absoluto, comparación y ordenamiento.",
    parent_topic_id: "t-1",
    is_locked_by_default: true,
  },
  {
    id: "t-1-2",
    level: 1,
    title: "Potencias y Raíces",
    description: "Cuadrados, cubos, raíces cuadradas, raíces cúbicas, estimación de raíces irracionales.",
    parent_topic_id: "t-1",
    is_locked_by_default: true,
  },
  {
    id: "t-1-3",
    level: 1,
    title: "Introducción a Variables",
    description: "Expresiones algebraicas, evaluación de expresiones, traducción de lenguaje verbal a algebraico.",
    parent_topic_id: "t-1",
    is_locked_by_default: true,
  },
  {
    id: "t-1-4",
    level: 1,
    title: "Ecuaciones de Un Paso",
    description: "Resolución de ecuaciones simples sumando, restando, multiplicando o dividiendo ambos lados.",
    parent_topic_id: "t-1",
    is_locked_by_default: true,
  },
  {
    id: "t-1-5",
    level: 1,
    title: "Desigualdades Básicas",
    description: "Desigualdades en la recta numérica, resolución de desigualdades simples, notación de intervalos.",
    parent_topic_id: "t-1",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 2: Álgebra I ═══
  {
    id: "t-2",
    level: 2,
    title: "Álgebra I",
    description: "Leyes de exponentes, factorización, ecuaciones lineales, cuadráticas y sistemas de ecuaciones.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-2-1",
    level: 2,
    title: "Leyes de Exponentes",
    description: "Producto, cociente, potencia de potencia, exponente cero, exponentes negativos y fraccionarios.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-2",
    level: 2,
    title: "Polinomios y Operaciones",
    description: "Suma, resta, multiplicación de polinomios. Productos notables: binomio al cuadrado, diferencia de cuadrados.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-3",
    level: 2,
    title: "Factorización",
    description: "Factor común, diferencia de cuadrados, trinomio cuadrado perfecto, factorización por agrupación.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-4",
    level: 2,
    title: "Ecuaciones Lineales",
    description: "Ecuaciones de primer grado, ecuaciones con fracciones, problemas de aplicación.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-5",
    level: 2,
    title: "Sistemas de Ecuaciones",
    description: "Sistemas 2×2 por sustitución, eliminación y gráfico. Sistemas 3×3 introductorios.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-6",
    level: 2,
    title: "Ecuaciones Cuadráticas",
    description: "Factorización, fórmula general, completar el cuadrado, discriminante y naturaleza de raíces.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },
  {
    id: "t-2-7",
    level: 2,
    title: "Desigualdades y Valor Absoluto",
    description: "Desigualdades lineales, cuadráticas, ecuaciones con valor absoluto, desigualdades con valor absoluto.",
    parent_topic_id: "t-2",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 3: Álgebra II y Funciones ═══
  {
    id: "t-3",
    level: 3,
    title: "Álgebra II y Funciones",
    description: "Funciones, logaritmos, exponenciales, números complejos y sucesiones.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-3-1",
    level: 3,
    title: "Funciones: Concepto y Tipos",
    description: "Dominio, rango, funciones inyectivas/sobreyectivas/biyectivas, composición e inversa.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },
  {
    id: "t-3-2",
    level: 3,
    title: "Funciones Lineales y Cuadráticas",
    description: "Pendiente, intersecciones, forma canónica, vértice, gráficas, transformaciones.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },
  {
    id: "t-3-3",
    level: 3,
    title: "Logaritmos",
    description: "Definición, propiedades de logaritmos, cambio de base, ecuaciones logarítmicas y exponenciales.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },
  {
    id: "t-3-4",
    level: 3,
    title: "Funciones Exponenciales",
    description: "Crecimiento y decaimiento exponencial, base $e$, interés compuesto, modelado.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },
  {
    id: "t-3-5",
    level: 3,
    title: "Números Complejos",
    description: "Unidad imaginaria $i$, operaciones, plano complejo, forma polar, fórmula de Euler.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },
  {
    id: "t-3-6",
    level: 3,
    title: "Sucesiones y Series",
    description: "Sucesiones aritméticas y geométricas, fórmulas del término general, sumas parciales, series convergentes.",
    parent_topic_id: "t-3",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 4: Trigonometría y Geometría Analítica ═══
  {
    id: "t-4",
    level: 4,
    title: "Trigonometría y Geometría Analítica",
    description: "Funciones trigonométricas, identidades, ley de senos/cosenos, cónicas y coordenadas.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-4-1",
    level: 4,
    title: "Funciones Trigonométricas",
    description: "Seno, coseno, tangente; círculo unitario, radianes, gráficas, amplitud, periodo, desfase.",
    parent_topic_id: "t-4",
    is_locked_by_default: true,
  },
  {
    id: "t-4-2",
    level: 4,
    title: "Identidades Trigonométricas",
    description: "Pitagóricas, recíprocas, de ángulo doble, suma/diferencia, producto a suma.",
    parent_topic_id: "t-4",
    is_locked_by_default: true,
  },
  {
    id: "t-4-3",
    level: 4,
    title: "Ecuaciones Trigonométricas",
    description: "Resolución de ecuaciones trigonométricas, soluciones generales, ecuaciones con identidades.",
    parent_topic_id: "t-4",
    is_locked_by_default: true,
  },
  {
    id: "t-4-4",
    level: 4,
    title: "Ley de Senos y Cosenos",
    description: "Resolución de triángulos oblicuángulos, área de triángulos, aplicaciones.",
    parent_topic_id: "t-4",
    is_locked_by_default: true,
  },
  {
    id: "t-4-5",
    level: 4,
    title: "Geometría Analítica",
    description: "Distancia, punto medio, ecuación de la recta, circunferencia, parábola, elipse, hipérbola.",
    parent_topic_id: "t-4",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 5: Cálculo Diferencial ═══
  {
    id: "t-5",
    level: 5,
    title: "Cálculo Diferencial",
    description: "Límites, continuidad, derivadas y sus aplicaciones. El corazón del análisis matemático.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-5-1",
    level: 5,
    title: "Límites",
    description: "Concepto intuitivo, límites laterales, al infinito, indeterminaciones 0/0, ∞/∞, L'Hôpital.",
    parent_topic_id: "t-5",
    is_locked_by_default: true,
  },
  {
    id: "t-5-2",
    level: 5,
    title: "Continuidad",
    description: "Definición de continuidad, tipos de discontinuidad, Teorema del Valor Intermedio.",
    parent_topic_id: "t-5",
    is_locked_by_default: true,
  },
  {
    id: "t-5-3",
    level: 5,
    title: "La Derivada",
    description: "Definición por límites, interpretación geométrica, reglas de derivación, regla de la cadena.",
    parent_topic_id: "t-5",
    is_locked_by_default: true,
  },
  {
    id: "t-5-4",
    level: 5,
    title: "Derivadas de Funciones Especiales",
    description: "Derivadas trigonométricas, exponenciales, logarítmicas, implícitas, derivadas de orden superior.",
    parent_topic_id: "t-5",
    is_locked_by_default: true,
  },
  {
    id: "t-5-5",
    level: 5,
    title: "Aplicaciones de la Derivada",
    description: "Máximos/mínimos, puntos de inflexión, concavidad, optimización, razones de cambio relacionadas.",
    parent_topic_id: "t-5",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 6: Cálculo Integral ═══
  {
    id: "t-6",
    level: 6,
    title: "Cálculo Integral",
    description: "Integrales indefinidas y definidas, técnicas de integración y aplicaciones.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-6-1",
    level: 6,
    title: "Integral Indefinida",
    description: "Antiderivada, regla de la potencia inversa, integrales inmediatas, constante de integración.",
    parent_topic_id: "t-6",
    is_locked_by_default: true,
  },
  {
    id: "t-6-2",
    level: 6,
    title: "Técnicas de Integración",
    description: "Sustitución (cambio de variable), integración por partes, fracciones parciales, sustitución trigonométrica.",
    parent_topic_id: "t-6",
    is_locked_by_default: true,
  },
  {
    id: "t-6-3",
    level: 6,
    title: "Integral Definida",
    description: "Sumas de Riemann, Teorema Fundamental del Cálculo, propiedades de la integral definida.",
    parent_topic_id: "t-6",
    is_locked_by_default: true,
  },
  {
    id: "t-6-4",
    level: 6,
    title: "Aplicaciones de la Integral",
    description: "Área entre curvas, volúmenes de revolución (disco, arandela, cascarón), longitud de arco, trabajo.",
    parent_topic_id: "t-6",
    is_locked_by_default: true,
  },
  {
    id: "t-6-5",
    level: 6,
    title: "Integrales Impropias y Series",
    description: "Integrales impropias convergentes/divergentes, series de Taylor y Maclaurin, radio de convergencia.",
    parent_topic_id: "t-6",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 7: Cálculo Multivariable ═══
  {
    id: "t-7",
    level: 7,
    title: "Cálculo Multivariable",
    description: "Funciones de varias variables, derivadas parciales, integrales múltiples y campos vectoriales.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-7-1",
    level: 7,
    title: "Derivadas Parciales y Gradiente",
    description: "Derivadas parciales, gradiente, derivada direccional, plano tangente, regla de la cadena multivariable.",
    parent_topic_id: "t-7",
    is_locked_by_default: true,
  },
  {
    id: "t-7-2",
    level: 7,
    title: "Optimización Multivariable",
    description: "Puntos críticos, criterio de la segunda derivada (Hessiana), multiplicadores de Lagrange.",
    parent_topic_id: "t-7",
    is_locked_by_default: true,
  },
  {
    id: "t-7-3",
    level: 7,
    title: "Integrales Dobles y Triples",
    description: "Integrales iteradas, cambio de orden, coordenadas polares, cilíndricas, esféricas.",
    parent_topic_id: "t-7",
    is_locked_by_default: true,
  },
  {
    id: "t-7-4",
    level: 7,
    title: "Cálculo Vectorial",
    description: "Campos vectoriales, integrales de línea, flujo, Teorema de Green, divergencia, rotacional, Stokes.",
    parent_topic_id: "t-7",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 8: Álgebra Lineal ═══
  {
    id: "t-8",
    level: 8,
    title: "Álgebra Lineal",
    description: "Vectores, matrices, espacios vectoriales, transformaciones lineales, eigenvalues. Pilar de la ciencia de datos.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-8-1",
    level: 8,
    title: "Vectores y Operaciones",
    description: "Vectores en R² y R³, suma, escalar, producto punto, producto cruz, ángulo entre vectores, proyecciones.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },
  {
    id: "t-8-2",
    level: 8,
    title: "Matrices y Determinantes",
    description: "Operaciones matriciales, tipos de matrices, determinantes, propiedades, expansión por cofactores.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },
  {
    id: "t-8-3",
    level: 8,
    title: "Sistemas Lineales y Gauss",
    description: "Eliminación gaussiana, forma escalonada reducida, rango, nulidad, soluciones paramétricas.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },
  {
    id: "t-8-4",
    level: 8,
    title: "Espacios Vectoriales",
    description: "Subespacios, independencia lineal, base, dimensión, cambio de base, coordenadas.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },
  {
    id: "t-8-5",
    level: 8,
    title: "Transformaciones Lineales",
    description: "Definición, núcleo, imagen, representación matricial, isomorfismos.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },
  {
    id: "t-8-6",
    level: 8,
    title: "Eigenvalues y Diagonalización",
    description: "Polinomio característico, eigenvalores, eigenvectores, diagonalización, descomposición espectral, SVD.",
    parent_topic_id: "t-8",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 9: Ecuaciones Diferenciales ═══
  {
    id: "t-9",
    level: 9,
    title: "Ecuaciones Diferenciales",
    description: "EDOs de primer y segundo orden, sistemas, transformada de Laplace. Esencial para modelado.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-9-1",
    level: 9,
    title: "EDOs de Primer Orden",
    description: "Separables, lineales, exactas, factor integrante, problemas de valor inicial.",
    parent_topic_id: "t-9",
    is_locked_by_default: true,
  },
  {
    id: "t-9-2",
    level: 9,
    title: "EDOs de Segundo Orden",
    description: "Coeficientes constantes, ecuación característica, variación de parámetros, ecuaciones de Euler.",
    parent_topic_id: "t-9",
    is_locked_by_default: true,
  },
  {
    id: "t-9-3",
    level: 9,
    title: "Transformada de Laplace",
    description: "Definición, tabla de transformadas, transformada inversa, resolución de EDOs con Laplace.",
    parent_topic_id: "t-9",
    is_locked_by_default: true,
  },

  // ═══ NIVEL 10: Probabilidad, Estadística y Optimización (Data Science) ═══
  {
    id: "t-10",
    level: 10,
    title: "Matemáticas para Data Science",
    description: "Probabilidad, estadística inferencial, optimización y fundamentos que todo científico de datos necesita.",
    parent_topic_id: null,
    is_locked_by_default: true,
  },
  {
    id: "t-10-1",
    level: 10,
    title: "Probabilidad",
    description: "Axiomas, probabilidad condicional, Bayes, variables aleatorias, distribuciones discretas y continuas.",
    parent_topic_id: "t-10",
    is_locked_by_default: true,
  },
  {
    id: "t-10-2",
    level: 10,
    title: "Estadística Inferencial",
    description: "Estimadores, intervalos de confianza, pruebas de hipótesis, p-valor, regresión lineal, correlación.",
    parent_topic_id: "t-10",
    is_locked_by_default: true,
  },
  {
    id: "t-10-3",
    level: 10,
    title: "Optimización",
    description: "Gradiente descendente, optimización convexa, multiplicadores de Lagrange, programación lineal.",
    parent_topic_id: "t-10",
    is_locked_by_default: true,
  },
  {
    id: "t-10-4",
    level: 10,
    title: "Álgebra Lineal Aplicada a ML",
    description: "PCA, SVD aplicada, normas vectoriales, matrices de covarianza, kernel trick conceptual.",
    parent_topic_id: "t-10",
    is_locked_by_default: true,
  },
];

// ═══════════════════════════════════════════════════════════════
// BANCO DE PROBLEMAS: 150+ problemas cubriendo todos los subtemas
// ═══════════════════════════════════════════════════════════════

export const seedProblems: Problem[] = [
  // ────────────────────────────────────
  // NIVEL 0: ARITMÉTICA FUNDAMENTAL
  // ────────────────────────────────────

  // ── Operaciones Básicas (t-0-1) ──
  { id: "p-01-01", topic_id: "t-0-1", difficulty: 1,
    statement_latex: "Calcula: $15 + 27$",
    correct_answer_latex: "42",
    hint_1_latex: "Suma las unidades: $5 + 7 = 12$, lleva $1$.",
    hint_2_latex: "Luego decenas: $1 + 2 + 1 = 4$.",
    step_by_step_solution_latex: "$15 + 27 = 42$" },
  { id: "p-01-02", topic_id: "t-0-1", difficulty: 1,
    statement_latex: "Calcula: $(-4) \\times (-6)$",
    correct_answer_latex: "24",
    hint_1_latex: "Negativo por negativo da positivo.",
    hint_2_latex: "$4 \\times 6 = 24$",
    step_by_step_solution_latex: "$(-4) \\times (-6) = +(4 \\times 6) = 24$" },
  { id: "p-01-03", topic_id: "t-0-1", difficulty: 1,
    statement_latex: "Calcula: $144 \\div 12$",
    correct_answer_latex: "12",
    hint_1_latex: "¿Qué número multiplicado por $12$ da $144$?",
    hint_2_latex: "$12 \\times 12 = 144$",
    step_by_step_solution_latex: "$144 \\div 12 = 12$" },
  { id: "p-01-04", topic_id: "t-0-1", difficulty: 2,
    statement_latex: "Aplica la propiedad distributiva: $7 \\times (30 + 2)$",
    correct_answer_latex: "224",
    hint_1_latex: "$a(b + c) = ab + ac$",
    hint_2_latex: "$7 \\times 30 + 7 \\times 2 = 210 + 14$",
    step_by_step_solution_latex: "$7(30 + 2) = 7 \\times 30 + 7 \\times 2 = 210 + 14 = 224$" },

  // ── Fracciones (t-0-2) ──
  { id: "p-02-01", topic_id: "t-0-2", difficulty: 1,
    statement_latex: "Simplifica: $\\dfrac{12}{18}$",
    correct_answer_latex: "\\frac{2}{3}",
    hint_1_latex: "Busca el MCD de $12$ y $18$.",
    hint_2_latex: "MCD$(12, 18) = 6$. Divide ambos entre $6$.",
    step_by_step_solution_latex: "$\\dfrac{12}{18} = \\dfrac{12 \\div 6}{18 \\div 6} = \\dfrac{2}{3}$" },
  { id: "p-02-02", topic_id: "t-0-2", difficulty: 1,
    statement_latex: "Calcula: $\\dfrac{2}{5} + \\dfrac{1}{3}$",
    correct_answer_latex: "\\frac{11}{15}",
    hint_1_latex: "MCM$(5, 3) = 15$.",
    hint_2_latex: "$\\dfrac{6}{15} + \\dfrac{5}{15}$",
    step_by_step_solution_latex: "$\\dfrac{2}{5} + \\dfrac{1}{3} = \\dfrac{6}{15} + \\dfrac{5}{15} = \\dfrac{11}{15}$" },
  { id: "p-02-03", topic_id: "t-0-2", difficulty: 2,
    statement_latex: "Calcula: $\\dfrac{3}{4} \\times \\dfrac{8}{9}$",
    correct_answer_latex: "\\frac{2}{3}",
    hint_1_latex: "Multiplica numeradores y denominadores.",
    hint_2_latex: "$\\dfrac{24}{36}$. Simplifica.",
    step_by_step_solution_latex: "$\\dfrac{3 \\times 8}{4 \\times 9} = \\dfrac{24}{36} = \\dfrac{2}{3}$" },
  { id: "p-02-04", topic_id: "t-0-2", difficulty: 2,
    statement_latex: "Calcula: $\\dfrac{5}{6} \\div \\dfrac{2}{3}$",
    correct_answer_latex: "\\frac{5}{4}",
    hint_1_latex: "Dividir es multiplicar por el recíproco.",
    hint_2_latex: "$\\dfrac{5}{6} \\times \\dfrac{3}{2}$",
    step_by_step_solution_latex: "$\\dfrac{5}{6} \\div \\dfrac{2}{3} = \\dfrac{5}{6} \\times \\dfrac{3}{2} = \\dfrac{15}{12} = \\dfrac{5}{4}$" },
  { id: "p-02-05", topic_id: "t-0-2", difficulty: 3,
    statement_latex: "Calcula: $\\dfrac{7}{8} - \\dfrac{3}{4} + \\dfrac{1}{2}$",
    correct_answer_latex: "\\frac{5}{8}",
    hint_1_latex: "MCM$(8, 4, 2) = 8$.",
    hint_2_latex: "$\\dfrac{7}{8} - \\dfrac{6}{8} + \\dfrac{4}{8}$",
    step_by_step_solution_latex: "$\\dfrac{7}{8} - \\dfrac{6}{8} + \\dfrac{4}{8} = \\dfrac{7 - 6 + 4}{8} = \\dfrac{5}{8}$" },

  // ── Decimales (t-0-3) ──
  { id: "p-03-01", topic_id: "t-0-3", difficulty: 1,
    statement_latex: "Convierte $\\dfrac{3}{8}$ a decimal.",
    correct_answer_latex: "0.375",
    hint_1_latex: "Divide $3 \\div 8$.",
    hint_2_latex: "$3.000 \\div 8 = 0.375$",
    step_by_step_solution_latex: "$\\dfrac{3}{8} = 3 \\div 8 = 0.375$" },
  { id: "p-03-02", topic_id: "t-0-3", difficulty: 2,
    statement_latex: "Calcula: $3.14 \\times 2.5$",
    correct_answer_latex: "7.85",
    hint_1_latex: "Multiplica como enteros: $314 \\times 25$.",
    hint_2_latex: "$314 \\times 25 = 7850$. Coloca 3 decimales (2+1).",
    step_by_step_solution_latex: "$3.14 \\times 2.5 = 7.850 = 7.85$" },

  // ── Porcentajes (t-0-4) ──
  { id: "p-04-01", topic_id: "t-0-4", difficulty: 1,
    statement_latex: "¿Cuánto es el $25\\%$ de $80$?",
    correct_answer_latex: "20",
    hint_1_latex: "$25\\% = 0.25$",
    hint_2_latex: "$0.25 \\times 80$",
    step_by_step_solution_latex: "$25\\% \\text{ de } 80 = 0.25 \\times 80 = 20$" },
  { id: "p-04-02", topic_id: "t-0-4", difficulty: 2,
    statement_latex: "Un producto cuesta \\$120 y tiene $15\\%$ de descuento. ¿Precio final?",
    correct_answer_latex: "102",
    hint_1_latex: "Descuento $= 0.15 \\times 120$.",
    hint_2_latex: "Descuento $= 18$. Precio $= 120 - 18$.",
    step_by_step_solution_latex: "Descuento $= 0.15 \\times 120 = 18$. Precio final $= 120 - 18 = 102$" },
  { id: "p-04-03", topic_id: "t-0-4", difficulty: 2,
    statement_latex: "Si $45$ es el $60\\%$ de un número, ¿cuál es ese número?",
    correct_answer_latex: "75",
    hint_1_latex: "$0.60 \\times x = 45$",
    hint_2_latex: "$x = 45 \\div 0.60$",
    step_by_step_solution_latex: "$x = \\dfrac{45}{0.60} = 75$" },

  // ── Orden de Operaciones (t-0-5) ──
  { id: "p-05-01", topic_id: "t-0-5", difficulty: 2,
    statement_latex: "Evalúa: $3 + 4 \\times 2 - 1$",
    correct_answer_latex: "10",
    hint_1_latex: "Multiplicación primero: $4 \\times 2 = 8$.",
    hint_2_latex: "$3 + 8 - 1 = 10$",
    step_by_step_solution_latex: "$4 \\times 2 = 8$, luego $3 + 8 - 1 = 10$" },
  { id: "p-05-02", topic_id: "t-0-5", difficulty: 3,
    statement_latex: "Evalúa: $2 \\times (3 + 5)^2 \\div 4$",
    correct_answer_latex: "32",
    hint_1_latex: "Paréntesis: $3 + 5 = 8$.",
    hint_2_latex: "$8^2 = 64$. Luego $2 \\times 64 \\div 4$.",
    step_by_step_solution_latex: "$2 \\times (8)^2 \\div 4 = 2 \\times 64 \\div 4 = 128 \\div 4 = 32$" },
  { id: "p-05-03", topic_id: "t-0-5", difficulty: 3,
    statement_latex: "Evalúa: $\\dfrac{6 + 2 \\times 3}{4 - 1}$",
    correct_answer_latex: "4",
    hint_1_latex: "Numerador: $6 + 6 = 12$.",
    hint_2_latex: "Denominador: $3$. $\\dfrac{12}{3} = 4$.",
    step_by_step_solution_latex: "Num: $6 + 2 \\times 3 = 12$. Den: $4 - 1 = 3$. $\\dfrac{12}{3} = 4$" },

  // ── Razones y Proporciones (t-0-6) ──
  { id: "p-06-01", topic_id: "t-0-6", difficulty: 2,
    statement_latex: "Si $3$ manzanas cuestan \\$12, ¿cuánto cuestan $7$ manzanas?",
    correct_answer_latex: "28",
    hint_1_latex: "Precio unitario: $12 \\div 3$.",
    hint_2_latex: "$4 \\times 7 = 28$",
    step_by_step_solution_latex: "Precio unitario $= \\$4$. Total $= 4 \\times 7 = \\$28$" },
  { id: "p-06-02", topic_id: "t-0-6", difficulty: 2,
    statement_latex: "Si $\\dfrac{x}{5} = \\dfrac{12}{15}$, encuentra $x$.",
    correct_answer_latex: "4",
    hint_1_latex: "Simplifica $\\dfrac{12}{15} = \\dfrac{4}{5}$.",
    hint_2_latex: "$\\dfrac{x}{5} = \\dfrac{4}{5}$, entonces $x = 4$.",
    step_by_step_solution_latex: "$\\dfrac{12}{15} = \\dfrac{4}{5}$. Como $\\dfrac{x}{5} = \\dfrac{4}{5}$, $x = 4$." },

  // ────────────────────────────────────
  // NIVEL 1: PRE-ÁLGEBRA
  // ────────────────────────────────────

  // ── Enteros y Valor Absoluto (t-1-1) ──
  { id: "p-11-01", topic_id: "t-1-1", difficulty: 1,
    statement_latex: "Calcula: $|-7| + |3|$",
    correct_answer_latex: "10",
    hint_1_latex: "$|-7| = 7$",
    hint_2_latex: "$7 + 3 = 10$",
    step_by_step_solution_latex: "$|-7| + |3| = 7 + 3 = 10$" },
  { id: "p-11-02", topic_id: "t-1-1", difficulty: 2,
    statement_latex: "Calcula: $(-8) - (-3) + (-2)$",
    correct_answer_latex: "-7",
    hint_1_latex: "$(-8) - (-3) = -8 + 3 = -5$",
    hint_2_latex: "$-5 + (-2) = -7$",
    step_by_step_solution_latex: "$(-8) - (-3) + (-2) = -8 + 3 - 2 = -7$" },

  // ── Potencias y Raíces (t-1-2) ──
  { id: "p-12-01", topic_id: "t-1-2", difficulty: 1,
    statement_latex: "Calcula: $2^5$",
    correct_answer_latex: "32",
    hint_1_latex: "$2^5 = 2 \\times 2 \\times 2 \\times 2 \\times 2$",
    hint_2_latex: "$4 \\times 4 \\times 2 = 32$",
    step_by_step_solution_latex: "$2^5 = 32$" },
  { id: "p-12-02", topic_id: "t-1-2", difficulty: 2,
    statement_latex: "Calcula: $\\sqrt{196}$",
    correct_answer_latex: "14",
    hint_1_latex: "$14^2 = ?$",
    hint_2_latex: "$14 \\times 14 = 196$",
    step_by_step_solution_latex: "$\\sqrt{196} = 14$ porque $14^2 = 196$" },
  { id: "p-12-03", topic_id: "t-1-2", difficulty: 2,
    statement_latex: "Calcula: $\\sqrt[3]{-27}$",
    correct_answer_latex: "-3",
    hint_1_latex: "$(-3)^3 = ?$",
    hint_2_latex: "$(-3)(-3)(-3) = -27$",
    step_by_step_solution_latex: "$\\sqrt[3]{-27} = -3$ porque $(-3)^3 = -27$" },

  // ── Variables (t-1-3) ──
  { id: "p-13-01", topic_id: "t-1-3", difficulty: 1,
    statement_latex: "Si $x = 3$, evalúa $4x + 7$.",
    correct_answer_latex: "19",
    hint_1_latex: "Sustituye $x = 3$: $4(3) + 7$.",
    hint_2_latex: "$12 + 7 = 19$",
    step_by_step_solution_latex: "$4(3) + 7 = 12 + 7 = 19$" },
  { id: "p-13-02", topic_id: "t-1-3", difficulty: 2,
    statement_latex: "Si $a = 2$ y $b = -3$, evalúa $a^2 - 2ab + b^2$.",
    correct_answer_latex: "25",
    hint_1_latex: "Nota: $a^2 - 2ab + b^2 = (a - b)^2$.",
    hint_2_latex: "$(2 - (-3))^2 = 5^2$",
    step_by_step_solution_latex: "$(a - b)^2 = (2 - (-3))^2 = 5^2 = 25$" },

  // ── Ecuaciones de Un Paso (t-1-4) ──
  { id: "p-14-01", topic_id: "t-1-4", difficulty: 1,
    statement_latex: "Resuelve: $x + 9 = 15$",
    correct_answer_latex: "x=6",
    hint_1_latex: "Resta $9$ de ambos lados.",
    hint_2_latex: "$x = 15 - 9$",
    step_by_step_solution_latex: "$x = 15 - 9 = 6$" },
  { id: "p-14-02", topic_id: "t-1-4", difficulty: 1,
    statement_latex: "Resuelve: $3x = 21$",
    correct_answer_latex: "x=7",
    hint_1_latex: "Divide ambos lados entre $3$.",
    hint_2_latex: "$x = 21 \\div 3$",
    step_by_step_solution_latex: "$x = \\dfrac{21}{3} = 7$" },

  // ── Desigualdades Básicas (t-1-5) ──
  { id: "p-15-01", topic_id: "t-1-5", difficulty: 2,
    statement_latex: "Resuelve: $2x - 3 > 7$",
    correct_answer_latex: "x>5",
    hint_1_latex: "Suma $3$: $2x > 10$.",
    hint_2_latex: "Divide entre $2$: $x > 5$.",
    step_by_step_solution_latex: "$2x > 10 \\Rightarrow x > 5$" },

  // ────────────────────────────────────
  // NIVEL 2: ÁLGEBRA I
  // ────────────────────────────────────

  // ── Leyes de Exponentes (t-2-1) ──
  { id: "p-21-01", topic_id: "t-2-1", difficulty: 1,
    statement_latex: "Simplifica: $x^3 \\cdot x^5$",
    correct_answer_latex: "x^{8}",
    hint_1_latex: "$x^a \\cdot x^b = x^{a+b}$",
    hint_2_latex: "$3 + 5 = 8$",
    step_by_step_solution_latex: "$x^3 \\cdot x^5 = x^{3+5} = x^8$" },
  { id: "p-21-02", topic_id: "t-2-1", difficulty: 2,
    statement_latex: "Simplifica: $\\dfrac{x^7}{x^3}$",
    correct_answer_latex: "x^{4}",
    hint_1_latex: "$\\dfrac{x^a}{x^b} = x^{a-b}$",
    hint_2_latex: "$7 - 3 = 4$",
    step_by_step_solution_latex: "$\\dfrac{x^7}{x^3} = x^{7-3} = x^4$" },
  { id: "p-21-03", topic_id: "t-2-1", difficulty: 3,
    statement_latex: "Simplifica: $(2x^3)^4$",
    correct_answer_latex: "16x^{12}",
    hint_1_latex: "$(ab)^n = a^n b^n$",
    hint_2_latex: "$2^4 = 16$, $(x^3)^4 = x^{12}$",
    step_by_step_solution_latex: "$(2x^3)^4 = 2^4 x^{12} = 16x^{12}$" },
  { id: "p-21-04", topic_id: "t-2-1", difficulty: 2,
    statement_latex: "Simplifica: $x^{-3}$ (escribe con exponente positivo).",
    correct_answer_latex: "\\frac{1}{x^{3}}",
    hint_1_latex: "$x^{-n} = \\dfrac{1}{x^n}$",
    hint_2_latex: "Solo aplica la definición.",
    step_by_step_solution_latex: "$x^{-3} = \\dfrac{1}{x^3}$" },

  // ── Polinomios (t-2-2) ──
  { id: "p-22-01", topic_id: "t-2-2", difficulty: 2,
    statement_latex: "Expande: $(x + 3)^2$",
    correct_answer_latex: "x^{2}+6x+9",
    hint_1_latex: "$(a+b)^2 = a^2 + 2ab + b^2$",
    hint_2_latex: "$x^2 + 2(x)(3) + 3^2$",
    step_by_step_solution_latex: "$(x+3)^2 = x^2 + 6x + 9$" },
  { id: "p-22-02", topic_id: "t-2-2", difficulty: 2,
    statement_latex: "Expande: $(2x - 1)(x + 4)$",
    correct_answer_latex: "2x^{2}+7x-4",
    hint_1_latex: "Usa FOIL o la distributiva.",
    hint_2_latex: "$2x^2 + 8x - x - 4$",
    step_by_step_solution_latex: "$2x(x) + 2x(4) - 1(x) - 1(4) = 2x^2 + 8x - x - 4 = 2x^2 + 7x - 4$" },

  // ── Factorización (t-2-3) ──
  { id: "p-23-01", topic_id: "t-2-3", difficulty: 2,
    statement_latex: "Factoriza: $x^2 - 9$",
    correct_answer_latex: "(x-3)(x+3)",
    hint_1_latex: "Diferencia de cuadrados: $a^2 - b^2 = (a-b)(a+b)$.",
    hint_2_latex: "$x^2 - 3^2$",
    step_by_step_solution_latex: "$x^2 - 9 = (x-3)(x+3)$" },
  { id: "p-23-02", topic_id: "t-2-3", difficulty: 3,
    statement_latex: "Factoriza: $x^2 + 5x + 6$",
    correct_answer_latex: "(x+2)(x+3)",
    hint_1_latex: "Busca $a, b$ con $ab = 6$ y $a+b = 5$.",
    hint_2_latex: "$a=2, b=3$.",
    step_by_step_solution_latex: "$x^2 + 5x + 6 = (x+2)(x+3)$" },
  { id: "p-23-03", topic_id: "t-2-3", difficulty: 3,
    statement_latex: "Factoriza: $6x^2 + 11x - 10$",
    correct_answer_latex: "(2x+5)(3x-2)",
    hint_1_latex: "Busca pares que multipliquen $6 \\times (-10) = -60$ y sumen $11$.",
    hint_2_latex: "$15 + (-4) = 11$ y $15 \\times (-4) = -60$.",
    step_by_step_solution_latex: "$6x^2 + 15x - 4x - 10 = 3x(2x+5) - 2(2x+5) = (2x+5)(3x-2)$" },

  // ── Ecuaciones Lineales (t-2-4) ──
  { id: "p-24-01", topic_id: "t-2-4", difficulty: 1,
    statement_latex: "Resuelve: $2x + 5 = 13$",
    correct_answer_latex: "x=4",
    hint_1_latex: "Resta $5$: $2x = 8$.",
    hint_2_latex: "Divide entre $2$.",
    step_by_step_solution_latex: "$2x = 8 \\Rightarrow x = 4$" },
  { id: "p-24-02", topic_id: "t-2-4", difficulty: 2,
    statement_latex: "Resuelve: $\\dfrac{x}{3} + 4 = \\dfrac{x}{2} - 1$",
    correct_answer_latex: "x=30",
    hint_1_latex: "Multiplica todo por $6$ (MCM de 3 y 2).",
    hint_2_latex: "$2x + 24 = 3x - 6$",
    step_by_step_solution_latex: "$2x + 24 = 3x - 6 \\Rightarrow 30 = x$" },

  // ── Sistemas de Ecuaciones (t-2-5) ──
  { id: "p-25-01", topic_id: "t-2-5", difficulty: 2,
    statement_latex: "Resuelve: $\\begin{cases} x + y = 7 \\\\ 2x - y = 2 \\end{cases}$",
    correct_answer_latex: "x=3, y=4",
    hint_1_latex: "Suma ambas ecuaciones.",
    hint_2_latex: "$3x = 9 \\Rightarrow x = 3$.",
    step_by_step_solution_latex: "Sumando: $3x = 9$, $x = 3$. Sustituyendo: $y = 7 - 3 = 4$." },
  { id: "p-25-02", topic_id: "t-2-5", difficulty: 3,
    statement_latex: "Resuelve: $\\begin{cases} 3x + 2y = 12 \\\\ x - y = 1 \\end{cases}$",
    correct_answer_latex: "x=\\frac{14}{5}, y=\\frac{9}{5}",
    hint_1_latex: "De la segunda: $x = 1 + y$. Sustituye en la primera.",
    hint_2_latex: "$3(1+y) + 2y = 12 \\Rightarrow 5y = 9$.",
    step_by_step_solution_latex: "$x = 1 + y$. $3(1+y)+2y=12 \\Rightarrow 5y = 9 \\Rightarrow y = \\dfrac{9}{5}$. $x = 1 + \\dfrac{9}{5} = \\dfrac{14}{5}$." },

  // ── Ecuaciones Cuadráticas (t-2-6) ──
  { id: "p-26-01", topic_id: "t-2-6", difficulty: 2,
    statement_latex: "Resuelve: $x^2 - 5x + 6 = 0$",
    correct_answer_latex: "x=2, x=3",
    hint_1_latex: "Factoriza el trinomio.",
    hint_2_latex: "$(x-2)(x-3) = 0$",
    step_by_step_solution_latex: "$(x-2)(x-3) = 0 \\Rightarrow x = 2$ o $x = 3$" },
  { id: "p-26-02", topic_id: "t-2-6", difficulty: 3,
    statement_latex: "Resuelve con la fórmula general: $2x^2 + 3x - 2 = 0$",
    correct_answer_latex: "x=\\frac{1}{2}, x=-2",
    hint_1_latex: "$a=2, b=3, c=-2$. Discriminante: $9 + 16 = 25$.",
    hint_2_latex: "$x = \\dfrac{-3 \\pm 5}{4}$",
    step_by_step_solution_latex: "$x = \\dfrac{-3 \\pm \\sqrt{25}}{4}$. $x_1 = \\dfrac{2}{4} = \\dfrac{1}{2}$, $x_2 = \\dfrac{-8}{4} = -2$." },
  { id: "p-26-03", topic_id: "t-2-6", difficulty: 3,
    statement_latex: "¿Cuántas soluciones reales tiene $x^2 + x + 1 = 0$?",
    correct_answer_latex: "0",
    hint_1_latex: "Calcula el discriminante $\\Delta = b^2 - 4ac$.",
    hint_2_latex: "$\\Delta = 1 - 4 = -3 < 0$. No hay raíces reales.",
    step_by_step_solution_latex: "$\\Delta = 1^2 - 4(1)(1) = -3 < 0$. Tiene $0$ soluciones reales." },

  // ── Desigualdades (t-2-7) ──
  { id: "p-27-01", topic_id: "t-2-7", difficulty: 2,
    statement_latex: "Resuelve: $|2x - 1| = 5$",
    correct_answer_latex: "x=3, x=-2",
    hint_1_latex: "$|A| = B$ implica $A = B$ o $A = -B$.",
    hint_2_latex: "$2x - 1 = 5 \\Rightarrow x = 3$; $2x - 1 = -5 \\Rightarrow x = -2$.",
    step_by_step_solution_latex: "Caso 1: $2x-1=5 \\Rightarrow x=3$. Caso 2: $2x-1=-5 \\Rightarrow x=-2$." },

  // ────────────────────────────────────
  // NIVEL 3: ÁLGEBRA II Y FUNCIONES
  // ────────────────────────────────────

  // ── Funciones (t-3-1) ──
  { id: "p-31-01", topic_id: "t-3-1", difficulty: 2,
    statement_latex: "Si $f(x) = 2x^2 - 3$, calcula $f(-2)$.",
    correct_answer_latex: "5",
    hint_1_latex: "Sustituye $x = -2$.",
    hint_2_latex: "$2(-2)^2 - 3 = 2(4) - 3$",
    step_by_step_solution_latex: "$f(-2) = 2(4) - 3 = 8 - 3 = 5$" },
  { id: "p-31-02", topic_id: "t-3-1", difficulty: 3,
    statement_latex: "Si $f(x) = 3x + 1$ y $g(x) = x^2$, calcula $(f \\circ g)(2)$.",
    correct_answer_latex: "13",
    hint_1_latex: "$(f \\circ g)(x) = f(g(x))$. Primero $g(2)$.",
    hint_2_latex: "$g(2) = 4$. Luego $f(4) = 13$.",
    step_by_step_solution_latex: "$g(2) = 4$. $f(4) = 3(4) + 1 = 13$." },

  // ── Funciones Lineales y Cuadráticas (t-3-2) ──
  { id: "p-32-01", topic_id: "t-3-2", difficulty: 2,
    statement_latex: "Encuentra el vértice de $f(x) = x^2 - 6x + 5$.",
    correct_answer_latex: "(3,-4)",
    hint_1_latex: "$x_v = -\\dfrac{b}{2a} = \\dfrac{6}{2} = 3$.",
    hint_2_latex: "$f(3) = 9 - 18 + 5 = -4$.",
    step_by_step_solution_latex: "$x_v = 3$. $f(3) = 9-18+5 = -4$. Vértice: $(3, -4)$." },

  // ── Logaritmos (t-3-3) ──
  { id: "p-33-01", topic_id: "t-3-3", difficulty: 2,
    statement_latex: "Calcula: $\\log_2(32)$",
    correct_answer_latex: "5",
    hint_1_latex: "$\\log_b(x) = n$ significa $b^n = x$.",
    hint_2_latex: "$2^5 = 32$",
    step_by_step_solution_latex: "$\\log_2(32) = 5$ porque $2^5 = 32$." },
  { id: "p-33-02", topic_id: "t-3-3", difficulty: 3,
    statement_latex: "Simplifica: $\\log(x^3) + \\log(x^2)$",
    correct_answer_latex: "5\\log(x)",
    hint_1_latex: "$\\log(a^n) = n\\log(a)$.",
    hint_2_latex: "$3\\log(x) + 2\\log(x)$.",
    step_by_step_solution_latex: "$\\log(x^3) + \\log(x^2) = 3\\log(x) + 2\\log(x) = 5\\log(x)$" },
  { id: "p-33-03", topic_id: "t-3-3", difficulty: 3,
    statement_latex: "Resuelve: $\\log_3(x) = 4$",
    correct_answer_latex: "x=81",
    hint_1_latex: "Convierte a forma exponencial.",
    hint_2_latex: "$3^4 = x$",
    step_by_step_solution_latex: "$\\log_3(x) = 4 \\Rightarrow x = 3^4 = 81$" },

  // ── Exponenciales (t-3-4) ──
  { id: "p-34-01", topic_id: "t-3-4", difficulty: 2,
    statement_latex: "Resuelve: $2^x = 16$",
    correct_answer_latex: "x=4",
    hint_1_latex: "Escribe $16$ como potencia de $2$.",
    hint_2_latex: "$2^x = 2^4$",
    step_by_step_solution_latex: "$2^x = 2^4 \\Rightarrow x = 4$" },

  // ── Números Complejos (t-3-5) ──
  { id: "p-35-01", topic_id: "t-3-5", difficulty: 2,
    statement_latex: "Calcula: $(3 + 2i)(1 - 4i)$",
    correct_answer_latex: "11-10i",
    hint_1_latex: "Usa FOIL y recuerda que $i^2 = -1$.",
    hint_2_latex: "$3 - 12i + 2i - 8i^2 = 3 - 10i + 8$",
    step_by_step_solution_latex: "$3(1) + 3(-4i) + 2i(1) + 2i(-4i) = 3 - 12i + 2i - 8i^2 = 3 - 10i + 8 = 11 - 10i$" },
  { id: "p-35-02", topic_id: "t-3-5", difficulty: 2,
    statement_latex: "Calcula $i^{10}$.",
    correct_answer_latex: "-1",
    hint_1_latex: "El ciclo de $i$: $i^1=i, i^2=-1, i^3=-i, i^4=1$.",
    hint_2_latex: "$10 = 4 \\times 2 + 2$. Entonces $i^{10} = i^2$.",
    step_by_step_solution_latex: "$10 \\div 4 = 2$ residuo $2$. $i^{10} = i^2 = -1$." },

  // ── Sucesiones y Series (t-3-6) ──
  { id: "p-36-01", topic_id: "t-3-6", difficulty: 2,
    statement_latex: "Encuentra el término 20 de la sucesión aritmética $3, 7, 11, 15, \\ldots$",
    correct_answer_latex: "79",
    hint_1_latex: "$a_n = a_1 + (n-1)d$. $d = 4$.",
    hint_2_latex: "$a_{20} = 3 + 19(4)$",
    step_by_step_solution_latex: "$a_{20} = 3 + 19 \\times 4 = 3 + 76 = 79$" },
  { id: "p-36-02", topic_id: "t-3-6", difficulty: 3,
    statement_latex: "Calcula la suma de la serie geométrica infinita: $\\displaystyle\\sum_{n=0}^{\\infty} \\left(\\dfrac{1}{3}\\right)^n$",
    correct_answer_latex: "\\frac{3}{2}",
    hint_1_latex: "$S = \\dfrac{a}{1 - r}$ para $|r| < 1$.",
    hint_2_latex: "$a = 1, r = \\dfrac{1}{3}$.",
    step_by_step_solution_latex: "$S = \\dfrac{1}{1 - 1/3} = \\dfrac{1}{2/3} = \\dfrac{3}{2}$" },

  // ────────────────────────────────────
  // NIVEL 4: TRIGONOMETRÍA
  // ────────────────────────────────────

  // ── Funciones Trig (t-4-1) ──
  { id: "p-41-01", topic_id: "t-4-1", difficulty: 1,
    statement_latex: "¿Cuánto vale $\\sin(30°)$?",
    correct_answer_latex: "\\frac{1}{2}",
    hint_1_latex: "Valor notable del seno.",
    hint_2_latex: "$30° = \\dfrac{\\pi}{6}$",
    step_by_step_solution_latex: "$\\sin(30°) = \\dfrac{1}{2}$" },
  { id: "p-41-02", topic_id: "t-4-1", difficulty: 2,
    statement_latex: "Calcula $\\cos(60°) + \\sin(90°)$",
    correct_answer_latex: "\\frac{3}{2}",
    hint_1_latex: "$\\cos(60°) = \\dfrac{1}{2}$",
    hint_2_latex: "$\\sin(90°) = 1$",
    step_by_step_solution_latex: "$\\dfrac{1}{2} + 1 = \\dfrac{3}{2}$" },
  { id: "p-41-03", topic_id: "t-4-1", difficulty: 2,
    statement_latex: "Convierte $135°$ a radianes.",
    correct_answer_latex: "\\frac{3\\pi}{4}",
    hint_1_latex: "Multiplica por $\\dfrac{\\pi}{180°}$.",
    hint_2_latex: "$135 \\times \\dfrac{\\pi}{180} = \\dfrac{135\\pi}{180}$. Simplifica.",
    step_by_step_solution_latex: "$135° \\times \\dfrac{\\pi}{180°} = \\dfrac{135\\pi}{180} = \\dfrac{3\\pi}{4}$" },

  // ── Identidades (t-4-2) ──
  { id: "p-42-01", topic_id: "t-4-2", difficulty: 2,
    statement_latex: "Simplifica: $\\sin^2(x) + \\cos^2(x)$",
    correct_answer_latex: "1",
    hint_1_latex: "Identidad pitagórica fundamental.",
    hint_2_latex: "Siempre es $1$.",
    step_by_step_solution_latex: "$\\sin^2(x) + \\cos^2(x) = 1$ (identidad pitagórica)." },
  { id: "p-42-02", topic_id: "t-4-2", difficulty: 3,
    statement_latex: "Simplifica: $\\dfrac{\\sin(2x)}{2\\cos(x)}$",
    correct_answer_latex: "\\sin(x)",
    hint_1_latex: "$\\sin(2x) = 2\\sin(x)\\cos(x)$.",
    hint_2_latex: "$\\dfrac{2\\sin(x)\\cos(x)}{2\\cos(x)}$. Simplifica.",
    step_by_step_solution_latex: "$\\dfrac{2\\sin(x)\\cos(x)}{2\\cos(x)} = \\sin(x)$" },

  // ── Ecuaciones Trig (t-4-3) ──
  { id: "p-43-01", topic_id: "t-4-3", difficulty: 3,
    statement_latex: "Resuelve $\\cos(x) = \\dfrac{1}{2}$ para $0 \\leq x < 2\\pi$. Da la menor solución.",
    correct_answer_latex: "\\frac{\\pi}{3}",
    hint_1_latex: "¿En qué ángulos vale $\\cos = 1/2$?",
    hint_2_latex: "$x = \\dfrac{\\pi}{3}$ y $x = \\dfrac{5\\pi}{3}$.",
    step_by_step_solution_latex: "$\\cos(x) = \\dfrac{1}{2}$ en $x = \\dfrac{\\pi}{3}$ (menor solución)." },

  // ── Geometría Analítica (t-4-5) ──
  { id: "p-45-01", topic_id: "t-4-5", difficulty: 2,
    statement_latex: "Encuentra la distancia entre $A(1, 2)$ y $B(4, 6)$.",
    correct_answer_latex: "5",
    hint_1_latex: "$d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$",
    hint_2_latex: "$\\sqrt{9 + 16}$",
    step_by_step_solution_latex: "$d = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5$" },
  { id: "p-45-02", topic_id: "t-4-5", difficulty: 2,
    statement_latex: "Encuentra la pendiente de la recta que pasa por $(2, 3)$ y $(6, 11)$.",
    correct_answer_latex: "2",
    hint_1_latex: "$m = \\dfrac{y_2 - y_1}{x_2 - x_1}$",
    hint_2_latex: "$\\dfrac{11 - 3}{6 - 2} = \\dfrac{8}{4}$",
    step_by_step_solution_latex: "$m = \\dfrac{11-3}{6-2} = \\dfrac{8}{4} = 2$" },

  // ────────────────────────────────────
  // NIVEL 5: CÁLCULO DIFERENCIAL
  // ────────────────────────────────────

  // ── Límites (t-5-1) ──
  { id: "p-51-01", topic_id: "t-5-1", difficulty: 2,
    statement_latex: "Calcula: $\\displaystyle\\lim_{x \\to 2} (3x^2 - 1)$",
    correct_answer_latex: "11",
    hint_1_latex: "Polinomio: sustitución directa.",
    hint_2_latex: "$3(4) - 1 = 11$",
    step_by_step_solution_latex: "$3(2)^2 - 1 = 12 - 1 = 11$" },
  { id: "p-51-02", topic_id: "t-5-1", difficulty: 3,
    statement_latex: "Calcula: $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sin(x)}{x}$",
    correct_answer_latex: "1",
    hint_1_latex: "Límite notable fundamental.",
    hint_2_latex: "Se demuestra con el Teorema del Sándwich.",
    step_by_step_solution_latex: "$\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sin(x)}{x} = 1$ (límite notable)." },
  { id: "p-51-03", topic_id: "t-5-1", difficulty: 3,
    statement_latex: "Calcula: $\\displaystyle\\lim_{x \\to 3} \\dfrac{x^2 - 9}{x - 3}$",
    correct_answer_latex: "6",
    hint_1_latex: "Factoriza el numerador: $x^2 - 9 = (x-3)(x+3)$.",
    hint_2_latex: "Simplifica: $\\dfrac{(x-3)(x+3)}{x-3} = x + 3$.",
    step_by_step_solution_latex: "$\\dfrac{(x-3)(x+3)}{x-3} = x + 3$. $\\lim_{x \\to 3}(x+3) = 6$." },

  // ── Continuidad (t-5-2) ──
  { id: "p-52-01", topic_id: "t-5-2", difficulty: 2,
    statement_latex: "¿Es $f(x) = \\dfrac{x^2 - 4}{x - 2}$ continua en $x = 2$? Responde sí o no.",
    correct_answer_latex: "no",
    hint_1_latex: "$f(2)$ no está definida (división por cero).",
    hint_2_latex: "Para ser continua, $f(a)$ debe existir, el límite debe existir, y deben ser iguales.",
    step_by_step_solution_latex: "$f(2)$ no está definida porque el denominador es $0$. No es continua en $x=2$." },

  // ── La Derivada (t-5-3) ──
  { id: "p-53-01", topic_id: "t-5-3", difficulty: 1,
    statement_latex: "Calcula la derivada de $f(x) = 3x^4$.",
    correct_answer_latex: "12x^{3}",
    hint_1_latex: "Regla de la potencia: $(x^n)' = nx^{n-1}$.",
    hint_2_latex: "$3 \\cdot 4 x^{4-1}$",
    step_by_step_solution_latex: "$f'(x) = 3 \\cdot 4x^3 = 12x^3$" },
  { id: "p-53-02", topic_id: "t-5-3", difficulty: 2,
    statement_latex: "Calcula: $\\dfrac{d}{dx}[x^3 + 5x^2 - 2x + 7]$",
    correct_answer_latex: "3x^{2}+10x-2",
    hint_1_latex: "Deriva término por término.",
    hint_2_latex: "$3x^2 + 10x - 2 + 0$",
    step_by_step_solution_latex: "$f'(x) = 3x^2 + 10x - 2$" },
  { id: "p-53-03", topic_id: "t-5-3", difficulty: 3,
    statement_latex: "Calcula la derivada de $f(x) = (3x+1)^5$ usando regla de la cadena.",
    correct_answer_latex: "15(3x+1)^{4}",
    hint_1_latex: "Cadena: $(g(x))^n \\cdot g'(x)$.",
    hint_2_latex: "$5(3x+1)^4 \\cdot 3$",
    step_by_step_solution_latex: "$f'(x) = 5(3x+1)^4 \\cdot 3 = 15(3x+1)^4$" },

  // ── Derivadas Especiales (t-5-4) ──
  { id: "p-54-01", topic_id: "t-5-4", difficulty: 2,
    statement_latex: "Calcula la derivada de $f(x) = \\sin(3x^2)$.",
    correct_answer_latex: "6x\\cos(3x^{2})",
    hint_1_latex: "Cadena: derivada externa × derivada interna.",
    hint_2_latex: "$\\cos(3x^2) \\cdot 6x$",
    step_by_step_solution_latex: "$f'(x) = \\cos(3x^2) \\cdot 6x = 6x\\cos(3x^2)$" },
  { id: "p-54-02", topic_id: "t-5-4", difficulty: 2,
    statement_latex: "Calcula: $\\dfrac{d}{dx}[e^{3x}]$",
    correct_answer_latex: "3e^{3x}",
    hint_1_latex: "$(e^{u})' = e^{u} \\cdot u'$.",
    hint_2_latex: "$u = 3x$, $u' = 3$.",
    step_by_step_solution_latex: "$\\dfrac{d}{dx}[e^{3x}] = e^{3x} \\cdot 3 = 3e^{3x}$" },
  { id: "p-54-03", topic_id: "t-5-4", difficulty: 2,
    statement_latex: "Calcula: $\\dfrac{d}{dx}[\\ln(5x)]$",
    correct_answer_latex: "\\frac{1}{x}",
    hint_1_latex: "$\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}$.",
    hint_2_latex: "$\\dfrac{5}{5x} = \\dfrac{1}{x}$",
    step_by_step_solution_latex: "$\\dfrac{d}{dx}[\\ln(5x)] = \\dfrac{5}{5x} = \\dfrac{1}{x}$" },

  // ── Aplicaciones de la Derivada (t-5-5) ──
  { id: "p-55-01", topic_id: "t-5-5", difficulty: 3,
    statement_latex: "Encuentra el mínimo de $f(x) = x^2 + 4x + 7$.",
    correct_answer_latex: "3",
    hint_1_latex: "$f'(x) = 2x + 4 = 0$.",
    hint_2_latex: "$x = -2$. $f(-2) = 4 - 8 + 7 = 3$.",
    step_by_step_solution_latex: "$f'(x) = 2x + 4 = 0 \\Rightarrow x = -2$. $f(-2) = 3$. $f''(x) = 2 > 0$ (mínimo)." },
  { id: "p-55-02", topic_id: "t-5-5", difficulty: 3,
    statement_latex: "Un rectángulo tiene perímetro $20$. ¿Cuál es el área máxima?",
    correct_answer_latex: "25",
    hint_1_latex: "Si $x$ es un lado: $2x + 2y = 20 \\Rightarrow y = 10 - x$.",
    hint_2_latex: "$A(x) = x(10-x) = 10x - x^2$. $A'(x) = 10 - 2x = 0$.",
    step_by_step_solution_latex: "$A = x(10-x)$. $A' = 10-2x = 0 \\Rightarrow x = 5$. $A(5) = 25$." },

  // ────────────────────────────────────
  // NIVEL 6: CÁLCULO INTEGRAL
  // ────────────────────────────────────

  // ── Integral Indefinida (t-6-1) ──
  { id: "p-61-01", topic_id: "t-6-1", difficulty: 2,
    statement_latex: "Calcula: $\\displaystyle\\int 4x^3 \\, dx$",
    correct_answer_latex: "x^{4}+C",
    hint_1_latex: "$\\int x^n dx = \\dfrac{x^{n+1}}{n+1} + C$",
    hint_2_latex: "$4 \\cdot \\dfrac{x^4}{4}$",
    step_by_step_solution_latex: "$4 \\cdot \\dfrac{x^4}{4} + C = x^4 + C$" },
  { id: "p-61-02", topic_id: "t-6-1", difficulty: 2,
    statement_latex: "Calcula: $\\displaystyle\\int (3x^2 + 2x - 5) \\, dx$",
    correct_answer_latex: "x^{3}+x^{2}-5x+C",
    hint_1_latex: "Integra término por término.",
    hint_2_latex: "$\\dfrac{3x^3}{3} + \\dfrac{2x^2}{2} - 5x$",
    step_by_step_solution_latex: "$x^3 + x^2 - 5x + C$" },
  { id: "p-61-03", topic_id: "t-6-1", difficulty: 2,
    statement_latex: "Calcula: $\\displaystyle\\int e^x \\, dx$",
    correct_answer_latex: "e^{x}+C",
    hint_1_latex: "La integral de $e^x$ es $e^x$.",
    hint_2_latex: "No olvides la constante $C$.",
    step_by_step_solution_latex: "$\\int e^x \\, dx = e^x + C$" },

  // ── Técnicas de Integración (t-6-2) ──
  { id: "p-62-01", topic_id: "t-6-2", difficulty: 3,
    statement_latex: "Calcula por sustitución: $\\displaystyle\\int 2x \\cdot e^{x^2} \\, dx$",
    correct_answer_latex: "e^{x^{2}}+C",
    hint_1_latex: "Sea $u = x^2$, entonces $du = 2x\\,dx$.",
    hint_2_latex: "$\\int e^u \\, du = e^u + C$.",
    step_by_step_solution_latex: "$u = x^2$, $du = 2x\\,dx$. $\\int e^u du = e^u + C = e^{x^2} + C$." },
  { id: "p-62-02", topic_id: "t-6-2", difficulty: 4,
    statement_latex: "Calcula por partes: $\\displaystyle\\int x e^x \\, dx$",
    correct_answer_latex: "xe^{x}-e^{x}+C",
    hint_1_latex: "$u = x$, $dv = e^x dx$.",
    hint_2_latex: "$du = dx$, $v = e^x$. $\\int u\\,dv = uv - \\int v\\,du$.",
    step_by_step_solution_latex: "$u=x, v=e^x$. $xe^x - \\int e^x dx = xe^x - e^x + C$." },

  // ── Integral Definida (t-6-3) ──
  { id: "p-63-01", topic_id: "t-6-3", difficulty: 2,
    statement_latex: "Calcula: $\\displaystyle\\int_0^1 2x \\, dx$",
    correct_answer_latex: "1",
    hint_1_latex: "$\\int 2x\\,dx = x^2$.",
    hint_2_latex: "$[x^2]_0^1 = 1 - 0$.",
    step_by_step_solution_latex: "$[x^2]_0^1 = 1^2 - 0^2 = 1$" },
  { id: "p-63-02", topic_id: "t-6-3", difficulty: 3,
    statement_latex: "Calcula: $\\displaystyle\\int_1^e \\dfrac{1}{x} \\, dx$",
    correct_answer_latex: "1",
    hint_1_latex: "$\\int \\dfrac{1}{x} dx = \\ln|x|$.",
    hint_2_latex: "$[\\ln|x|]_1^e = \\ln(e) - \\ln(1)$.",
    step_by_step_solution_latex: "$\\ln(e) - \\ln(1) = 1 - 0 = 1$" },

  // ── Aplicaciones (t-6-4) ──
  { id: "p-64-01", topic_id: "t-6-4", difficulty: 3,
    statement_latex: "Calcula el área entre $y = x^2$ y el eje $x$ de $x = 0$ a $x = 3$.",
    correct_answer_latex: "9",
    hint_1_latex: "$A = \\int_0^3 x^2 \\, dx$.",
    hint_2_latex: "$\\left[\\dfrac{x^3}{3}\\right]_0^3 = \\dfrac{27}{3}$.",
    step_by_step_solution_latex: "$\\int_0^3 x^2 dx = \\left[\\dfrac{x^3}{3}\\right]_0^3 = 9 - 0 = 9$." },

  // ── Series de Taylor (t-6-5) ──
  { id: "p-65-01", topic_id: "t-6-5", difficulty: 3,
    statement_latex: "Escribe los primeros 3 términos de la serie de Maclaurin de $e^x$.",
    correct_answer_latex: "1+x+\\frac{x^{2}}{2}",
    hint_1_latex: "$e^x = \\sum \\dfrac{x^n}{n!}$.",
    hint_2_latex: "$1 + x + \\dfrac{x^2}{2!}$",
    step_by_step_solution_latex: "$e^x \\approx 1 + x + \\dfrac{x^2}{2}$" },

  // ────────────────────────────────────
  // NIVEL 7: CÁLCULO MULTIVARIABLE
  // ────────────────────────────────────

  // ── Derivadas Parciales (t-7-1) ──
  { id: "p-71-01", topic_id: "t-7-1", difficulty: 2,
    statement_latex: "Calcula $\\dfrac{\\partial f}{\\partial x}$ si $f(x,y) = x^2y + 3xy^2$.",
    correct_answer_latex: "2xy+3y^{2}",
    hint_1_latex: "Trata $y$ como constante.",
    hint_2_latex: "$2xy + 3y^2$",
    step_by_step_solution_latex: "$\\dfrac{\\partial}{\\partial x}[x^2y] = 2xy$, $\\dfrac{\\partial}{\\partial x}[3xy^2] = 3y^2$. Total: $2xy + 3y^2$." },
  { id: "p-71-02", topic_id: "t-7-1", difficulty: 3,
    statement_latex: "Calcula el gradiente de $f(x,y) = x^2 + y^2$ en el punto $(3, 4)$.",
    correct_answer_latex: "(6,8)",
    hint_1_latex: "$\\nabla f = \\left(\\dfrac{\\partial f}{\\partial x}, \\dfrac{\\partial f}{\\partial y}\\right)$.",
    hint_2_latex: "$\\nabla f = (2x, 2y)$. En $(3,4)$: $(6, 8)$.",
    step_by_step_solution_latex: "$\\nabla f = (2x, 2y)$. En $(3,4)$: $\\nabla f = (6, 8)$." },

  // ── Optimización Multi (t-7-2) ──
  { id: "p-72-01", topic_id: "t-7-2", difficulty: 4,
    statement_latex: "Encuentra el punto crítico de $f(x,y) = x^2 + y^2 - 2x - 4y + 8$.",
    correct_answer_latex: "(1,2)",
    hint_1_latex: "$f_x = 2x - 2 = 0$ y $f_y = 2y - 4 = 0$.",
    hint_2_latex: "$x = 1, y = 2$.",
    step_by_step_solution_latex: "$f_x = 2x-2 = 0 \\Rightarrow x = 1$. $f_y = 2y-4 = 0 \\Rightarrow y = 2$. Punto: $(1,2)$." },

  // ── Integrales Dobles (t-7-3) ──
  { id: "p-73-01", topic_id: "t-7-3", difficulty: 3,
    statement_latex: "Calcula: $\\displaystyle\\int_0^1 \\int_0^2 (x + y) \\, dx \\, dy$",
    correct_answer_latex: "3",
    hint_1_latex: "Interna: $\\int_0^2(x+y)dx = [\\dfrac{x^2}{2}+xy]_0^2 = 2 + 2y$.",
    hint_2_latex: "Externa: $\\int_0^1(2+2y)dy = [2y+y^2]_0^1 = 3$.",
    step_by_step_solution_latex: "Interna: $2+2y$. Externa: $\\int_0^1(2+2y)dy = 2+1 = 3$." },

  // ────────────────────────────────────
  // NIVEL 8: ÁLGEBRA LINEAL
  // ────────────────────────────────────

  // ── Vectores (t-8-1) ──
  { id: "p-81-01", topic_id: "t-8-1", difficulty: 1,
    statement_latex: "Calcula $\\vec{u} \\cdot \\vec{v}$ si $\\vec{u} = (2, 3)$ y $\\vec{v} = (4, -1)$.",
    correct_answer_latex: "5",
    hint_1_latex: "$\\vec{u} \\cdot \\vec{v} = u_1v_1 + u_2v_2$.",
    hint_2_latex: "$2(4) + 3(-1) = 8 - 3$.",
    step_by_step_solution_latex: "$2(4) + 3(-1) = 8 - 3 = 5$" },
  { id: "p-81-02", topic_id: "t-8-1", difficulty: 2,
    statement_latex: "Calcula la norma de $\\vec{v} = (3, 4)$.",
    correct_answer_latex: "5",
    hint_1_latex: "$||\\vec{v}|| = \\sqrt{v_1^2 + v_2^2}$.",
    hint_2_latex: "$\\sqrt{9 + 16}$.",
    step_by_step_solution_latex: "$||\\vec{v}|| = \\sqrt{9 + 16} = \\sqrt{25} = 5$" },

  // ── Matrices y Determinantes (t-8-2) ──
  { id: "p-82-01", topic_id: "t-8-2", difficulty: 2,
    statement_latex: "Calcula el determinante de $A = \\begin{pmatrix} 2 & 3 \\\\ 1 & 4 \\end{pmatrix}$.",
    correct_answer_latex: "5",
    hint_1_latex: "$\\det = ad - bc$.",
    hint_2_latex: "$2(4) - 3(1)$.",
    step_by_step_solution_latex: "$\\det(A) = 2(4) - 3(1) = 8 - 3 = 5$" },
  { id: "p-82-02", topic_id: "t-8-2", difficulty: 3,
    statement_latex: "Calcula $AB$ si $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}$ y $B = \\begin{pmatrix} 5 \\\\ 6 \\end{pmatrix}$.",
    correct_answer_latex: "\\begin{pmatrix}17\\\\39\\end{pmatrix}",
    hint_1_latex: "Fila × Columna. Primera fila: $1(5) + 2(6)$.",
    hint_2_latex: "$17$ y $3(5)+4(6) = 39$.",
    step_by_step_solution_latex: "$\\begin{pmatrix}1(5)+2(6)\\\\3(5)+4(6)\\end{pmatrix} = \\begin{pmatrix}17\\\\39\\end{pmatrix}$" },

  // ── Eigenvalues (t-8-6) ──
  { id: "p-86-01", topic_id: "t-8-6", difficulty: 3,
    statement_latex: "Encuentra los eigenvalues de $A = \\begin{pmatrix} 3 & 1 \\\\ 0 & 2 \\end{pmatrix}$.",
    correct_answer_latex: "\\lambda=3, \\lambda=2",
    hint_1_latex: "$\\det(A - \\lambda I) = 0$.",
    hint_2_latex: "$(3-\\lambda)(2-\\lambda) = 0$.",
    step_by_step_solution_latex: "$(3-\\lambda)(2-\\lambda) = 0 \\Rightarrow \\lambda = 3, \\lambda = 2$." },

  // ────────────────────────────────────
  // NIVEL 9: ECUACIONES DIFERENCIALES
  // ────────────────────────────────────

  // ── EDO Primer Orden (t-9-1) ──
  { id: "p-91-01", topic_id: "t-9-1", difficulty: 3,
    statement_latex: "Resuelve: $\\dfrac{dy}{dx} = 2x$, con $y(0) = 1$.",
    correct_answer_latex: "y=x^{2}+1",
    hint_1_latex: "Integra ambos lados: $y = \\int 2x\\,dx$.",
    hint_2_latex: "$y = x^2 + C$. Usa $y(0) = 1$: $C = 1$.",
    step_by_step_solution_latex: "$y = x^2 + C$. $y(0) = 1 \\Rightarrow C = 1$. $y = x^2 + 1$." },
  { id: "p-91-02", topic_id: "t-9-1", difficulty: 3,
    statement_latex: "Resuelve la ED separable: $\\dfrac{dy}{dx} = \\dfrac{y}{x}$. Da la solución general.",
    correct_answer_latex: "y=Cx",
    hint_1_latex: "Separa: $\\dfrac{dy}{y} = \\dfrac{dx}{x}$.",
    hint_2_latex: "$\\ln|y| = \\ln|x| + C_1$.",
    step_by_step_solution_latex: "$\\int \\dfrac{dy}{y} = \\int \\dfrac{dx}{x}$. $\\ln|y| = \\ln|x| + C_1$. $y = Cx$." },

  // ── EDO Segundo Orden (t-9-2) ──
  { id: "p-92-01", topic_id: "t-9-2", difficulty: 3,
    statement_latex: "Resuelve: $y'' - 5y' + 6y = 0$.",
    correct_answer_latex: "y=C_1e^{2x}+C_2e^{3x}",
    hint_1_latex: "Ecuación característica: $r^2 - 5r + 6 = 0$.",
    hint_2_latex: "$(r-2)(r-3) = 0$. $r_1 = 2, r_2 = 3$.",
    step_by_step_solution_latex: "$r^2-5r+6=0 \\Rightarrow r=2,3$. $y = C_1 e^{2x} + C_2 e^{3x}$." },

  // ────────────────────────────────────
  // NIVEL 10: MATH PARA DATA SCIENCE
  // ────────────────────────────────────

  // ── Probabilidad (t-10-1) ──
  { id: "p-101-01", topic_id: "t-10-1", difficulty: 2,
    statement_latex: "Si $P(A)=0.3$ y $P(B)=0.5$ y $A,B$ independientes, calcula $P(A \\cap B)$.",
    correct_answer_latex: "0.15",
    hint_1_latex: "Independencia: $P(A \\cap B) = P(A) \\cdot P(B)$.",
    hint_2_latex: "$0.3 \\times 0.5$.",
    step_by_step_solution_latex: "$P(A \\cap B) = 0.3 \\times 0.5 = 0.15$" },
  { id: "p-101-02", topic_id: "t-10-1", difficulty: 3,
    statement_latex: "Una prueba médica tiene $95\\%$ sensibilidad. La enfermedad tiene prevalencia $1\\%$. Si la prueba sale positiva, ¿cuál es $P(\\text{enfermo}|+)$ aprox.? Falsos positivos: $5\\%$.",
    correct_answer_latex: "\\approx 0.16",
    hint_1_latex: "Usa Bayes: $P(E|+) = \\dfrac{P(+|E)P(E)}{P(+)}$.",
    hint_2_latex: "$P(+) = 0.95(0.01) + 0.05(0.99) = 0.059$.",
    step_by_step_solution_latex: "$P(E|+) = \\dfrac{0.95 \\times 0.01}{0.95(0.01)+0.05(0.99)} = \\dfrac{0.0095}{0.059} \\approx 0.16$." },

  // ── Estadística Inferencial (t-10-2) ──
  { id: "p-102-01", topic_id: "t-10-2", difficulty: 2,
    statement_latex: "Si $X \\sim N(\\mu, \\sigma^2)$ con $\\mu = 100$ y $\\sigma = 15$, ¿cuál es $P(X < 100)$?",
    correct_answer_latex: "0.5",
    hint_1_latex: "La distribución normal es simétrica alrededor de $\\mu$.",
    hint_2_latex: "$P(X < \\mu) = 0.5$ siempre.",
    step_by_step_solution_latex: "Por simetría de la normal: $P(X < \\mu) = 0.5$." },

  // ── Optimización (t-10-3) ──
  { id: "p-103-01", topic_id: "t-10-3", difficulty: 3,
    statement_latex: "El gradiente de $f(x,y) = x^2 + 2y^2$ en $(1,1)$ es $(2, 4)$. Si el learning rate es $\\alpha = 0.1$, ¿cuál es el nuevo punto tras un paso de gradient descent?",
    correct_answer_latex: "(0.8, 0.6)",
    hint_1_latex: "GD: $\\mathbf{x}_{\\text{new}} = \\mathbf{x} - \\alpha \\nabla f$.",
    hint_2_latex: "$(1 - 0.1 \\cdot 2, \\; 1 - 0.1 \\cdot 4) = (0.8, 0.6)$.",
    step_by_step_solution_latex: "$(1,1) - 0.1(2,4) = (1-0.2, 1-0.4) = (0.8, 0.6)$." },

  // ── Álgebra Lineal Aplicada (t-10-4) ──
  { id: "p-104-01", topic_id: "t-10-4", difficulty: 3,
    statement_latex: "La matriz de covarianza es $\\Sigma = \\begin{pmatrix} 4 & 2 \\\\ 2 & 3 \\end{pmatrix}$. ¿Es definida positiva? (eigenvalues > 0). Calcula $\\det(\\Sigma)$.",
    correct_answer_latex: "8",
    hint_1_latex: "$\\det = 4(3) - 2(2)$.",
    hint_2_latex: "$12 - 4 = 8 > 0$. $\\text{traza} = 7 > 0$.",
    step_by_step_solution_latex: "$\\det(\\Sigma) = 12 - 4 = 8$. Como $\\det > 0$ y traza $> 0$, es definida positiva." },
];

